[package]
name = "sca"
version = "0.1.0"
authors = ["kien6034 <trinhtrungkientb99@gmail.com>"]
edition = "2018"


# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]
# use library feature to disable all instantiate/execute/query exports
library = []


[dependencies]
cosmwasm-std = "1.0.0"
cosmwasm-storage = "1.0.0"
cw-storage-plus = "0.13.2"
cw0 = "0.10.3"
cw2 = "0.13.2"
cw20 = "0.13.2"
cw-controllers = "0.13.2"
schemars = "0.8.8"
serde = { version = "1.0.137", default-features = false, features = ["derive"] }
thiserror = "1.0.31"

[dev-dependencies]
cosmwasm-schema = { version = "0.16.0" }
